### ISSUE TITLE
Does not work with local remotes

### ISSUE THREAD

**Issue by Tatsh** [msiemens/PyGitUp#56]
I know that sounds strange. But if you have a local directory as one of your remotes, the script fails:

```Python traceback
Traceback (most recent call last):
  File "/Users/audvare/.virtualenvs/zzz/bin/git-up", line 11, in <module>
    sys.exit(run())
  File "/Users/audvare/.virtualenvs/zzz/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/audvare/.virtualenvs/zzz/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/audvare/.virtualenvs/zzz/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/audvare/.virtualenvs/zzz/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/audvare/.virtualenvs/zzz/lib/python2.7/site-packages/PyGitUp/gitup.py", line 600, in run
    gitup.run()
  File "/Users/audvare/.virtualenvs/zzz/lib/python2.7/site-packages/PyGitUp/gitup.py", line 182, in run
    self.fetch()
  File "/Users/audvare/.virtualenvs/zzz/lib/python2.7/site-packages/PyGitUp/gitup.py", line 301, in fetch
    self.git.fetch(tostdout=True, *fetch_args, **fetch_kwargs)
  File "/Users/audvare/.virtualenvs/zzz/lib/python2.7/site-packages/PyGitUp/git_wrapper.py", line 123, in <lambda>
    return lambda *args, **kwargs: self.run(name, *args, **kwargs)
  File "/Users/audvare/.virtualenvs/zzz/lib/python2.7/site-packages/PyGitUp/git_wrapper.py", line 118, in run
    raise GitError(message, stderr=error.stderr, stdout=stdout)
  File "/Users/audvare/.virtualenvs/zzz/lib/python2.7/site-packages/PyGitUp/git_wrapper.py", line 230, in __init__
    super(GitError, self).__init__(None, None, stderr)
  File "/Users/audvare/.virtualenvs/zzz/lib/python2.7/site-packages/git/exc.py", line 74, in __init__
    super(GitCommandError, self).__init__(command, status, stderr, stdout)
  File "/Users/audvare/.virtualenvs/zzz/lib/python2.7/site-packages/git/exc.py", line 38, in __init__
    command = command.split()
AttributeError: 'NoneType' object has no attribute 'split'
```

To reproduce:

```bash
cd $myrepo
git remote add other ~/somewhere/local
git up
```

**Comment by msiemens** [comment]
That's really interesting, thanks for reporting! I suspect that the new GitPython release v2.0 somehow breaks PyGitUp as it seems to have worked fine with v1.0. I'll investiage this. BTW also breaks the test suite as it too uses local remotes :smile:

**Comment by msiemens** [comment]
Seems to be fixed in 2aa1190c5e874881acf1a110a41a820efe4ded42, I'll release a new version of PyGitUp soon :)
