### ISSUE TITLE
Broken with gitpython 1.0.0

### ISSUE THREAD

**Issue by quasipedia** [msiemens/PyGitUp#28]
Git-up has stopped working for me with the error:

    Traceback (most recent call last):
      File "/usr/bin/git-up", line 9, in <module>
        load_entry_point('git-up==1.3.0', 'console_scripts', 'git-up')()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2345, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/bin/gitup.py", line 66, in <module>
        from git import Repo, GitCmdObjectDB
      File "/usr/lib/python2.7/site-packages/git/__init__.py", line 37, in <module>
        from git.refs import *
      File "/usr/lib/python2.7/site-packages/git/refs/__init__.py", line 4, in <module>
        from .symbolic import *
      File "/usr/lib/python2.7/site-packages/git/refs/symbolic.py", line 11, in <module>
        from gitdb.exc import (
    ImportError: cannot import name BadName

A quick googling seems to indicate it's an upstream bug in gitpython v.1.0.0 which has been fixed in 1.0.1 (See: https://github.com/gitpython-developers/GitPython/issues/231)

**Comment by quasipedia** [comment]
I shall add: the bug is there only on Python2.7, the library works with Python3.4.

**Comment by msiemens** [comment]
Thanks for reporting! I've updated the dependcies in 7cb55e531706a0791d8010dba31a8e80cbea2784. The Travis tests passed, but I've messed up my local Windows setup and wasn't able to run the test suite there. Could someone else with a Windows machine verify the test suite is passing on Python 2.7? (`nosetests -v` in the source directory)

**Comment by msiemens** [comment]
Finally found time to fix my local setup. Test suite passes so far. Closing
